site_name: Mim1q's Mod Wiki
site_url: https://mim1q.github.io/mod-wiki/
site_dir: ./build/

nav:
  - Home: index.md
  - Mine Cells:
      - About Mine Cells: minecells/index.md
      - Tips & Progression Guide: minecells/progression-guide.md
      - Technical Info:
          - Configuration: minecells/config.md
          - Updating Mine Cells: minecells/updating.md
      - Datapacks:
          - Spawner Rune Definitions: minecells/spawner_runes.md
          - Custom Cell Crafter Recipes: minecells/cell_crafter_recipes.md

markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.admonition:
      types:
        - new
        - settings
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
  - pymdownx.blocks.details:

plugins:
  - search
  - macros

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    - scheme: slate
      primary: deep purple
      accent: purple
  favicon: img/favicon.png
extra_css:
  - stylesheets/extra.css
